### ISSUE TITLE
make a .env.example

### ISSUE THREAD

**Issue by yawn999** [comicallybad/ComicallyBot2.0#17]
making a ,env example for users to help make PR and/or fix bug reports. for example, i cant find out where to put my MongoURI goes.

**Comment by comicallybad** [comment]
.env skeleton has been posted. In the future I may revert back to being able to use a free cleverbot API so you don't need a paid token. Your MongoURL goes in events -> client -> ready.js. Any other questions?

**Comment by yawn999** [comment]
that should be it, thanks. I was gonna fork and try to make a mute handler.

**Comment by comicallybad** [comment]
no prob, you making a mute handler off of the discord-anti-spam? Or something else?

**Comment by yawn999** [comment]
actually, what is the  "DMCHANNELID" for?

**Comment by yawn999** [comment]
> no prob, you making a mute handler off of the discord-anti-spam? Or something else?
Will try to do with discord-anti-spam.

**Comment by comicallybad** [comment]
> actually, what is the "DMCHANNELID" for?

DMCHANNELID is your dm channel ID with the bot for the owner _cdms to clean your DM's with the bot. I just made it since it would flood with errors sometimes. Wanted to be able to have the bot delete it's own messages in my dm's. So you would just right click on your DM conversation with the bot and copy ID and that's your DMCHANNELID, it's not used for anything besides that, I would like to eventually make it so everyone can use it, however, it is kind of hard to find a DM channel for any user, idk why but the documentation does not provide any way of doing it easily.

**Comment by comicallybad** [comment]
> > Will try to do with discord-anti-spam.

also might be doing this myself later on. Right now it works okay, but I do want to add some more things, maybe replace the discord-anti-spam embed that is logged too. Many things to change. My discord-v13-branch is what I have been running now for a couple of months still debugging to this day on very minor errors, but soon I will be adding interactions with slash commands and stuff.

**Comment by comicallybad** [comment]
If you want though feel free to create any PR's, would love to see what you do. Haven't had anyone else contribute lol. So might be interested in what you plan!

**Comment by yawn999** [comment]
great! ill start sometime today (Monday) during classes. I might also help with the v13 rewrite if you mind. :)

**Comment by yawn999** [comment]
> > actually, what is the "DMCHANNELID" for?
> 
> DMCHANNELID is your dm channel ID with the bot for the owner _cdms to clean your DM's with the bot. I just made it since it would flood with errors sometimes. Wanted to be able to have the bot delete it's own messages in my dm's. So you would just right click on your DM conversation with the bot and copy ID and that's your DMCHANNELID, it's not used for anything besides that, I would like to eventually make it so everyone can use it, however, it is kind of hard to find a DM channel for any user, idk why but the documentation does not provide any way of doing it easily.

ohh. i think i kinda get this now.

**Comment by yawn999** [comment]
are logs able to get changed without the database? reports do to a different channel other than a channel with the name "reports"

**Comment by comicallybad** [comment]
> are logs able to get changed without the database? reports do to a different channel other than a channel with the name "reports"

 Currently no. What I really would like to do is have a website like dyne where people can visualize a lot of the setup like adding members or roles, adding moderators. Toggling auto moderation stuff. Setting the suggestion channel, the logging and reporting channel to whatever channel they want. I know just going off commands can be difficult to understand but I would like to use whatever log channel name they choose. It’s just implemented all widely that it’s kind of hard. Would just take some time. Would have to say like let logChannel = await db.findOne({guildID: guildID});
If(!logchannel.logchannel)
 logChannel = await guild.channels.cache.map(c => c.name === mod-logs);


like that would have to be added in a lot of spots. I can probably work on that though.

**Comment by comicallybad** [comment]
I might finally just put a PR for the v13 update. I’ve fixed almost every issue I’ve had. But things like discord-anti-spam now use the timeout instead of actually a mute role. So I’m not sure if I wanna update that and go that route. Most bots are starting to use timeout instead of mute now since it’s much easier. No role to make or anything. So that’s also something to think about changing towards.

**Comment by comicallybad** [comment]
Closed as I have created a .envSkeleton
